version: '3.9'

services:

  tic-tac-toe:
    container_name: tic-tac-toe
    image: tic-tac-toe:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1234:1234
      - 1235:1235
    volumes:
      - .:/home/node
      - /home/node/node_modules
    command: ['start']
    working_dir: /home/node/